### ISSUE TITLE
Output filter :empty and :notempty not working

### ISSUE THREAD

**Issue by rwam** [Bruno17/MIGX#143]
Hello,

I have a little problem with empty migx-variables. In my case there is a migx-grid. If I delete all input of the grid then output filter :empty or :notempty don't work. Because the content of the variable isn't empty ;( It consists an empty JSON array `[]` So I cannot check with

```
[[*myMigxVariable:empty=`do this`:notempty=`do that`]]
```

Instead of the mentioned statement I must use

```
[[*myMigxVariable:ne=``:and:ne=`[]`:then=`do this`:else=`do that`]]
```

I use Revolution 2.2.10 with MIGX 2.6.7

Ciao
Ralf

**Comment by Lefthandmedia** [comment]
i think its a bug too. empty should be empty.

**Comment by FerX** [comment]
It is not a bug.
migx save data as array converted to json.
an empty array to json is `[]`

create snippet **jsonEmpty**

```
<?php
return empty($input) || empty($modx->fromJSON($input));

```

**Comment by Bruno17** [comment]
there is also an &emptyTpl - property, which is used, if no results. Can be a chunk or @CODE: can be used

**Comment by Lefthandmedia** [comment]
@ FerX i understand the technical reason why it's not empty. But i still think it is a bug. Since MIGX is a TV it should behave like one. every TV, when it has no value, is manipulatable with outputfilters. So logicaly when a MIGX TV has no entries the :empty filter should return true. The fact that there is an empty json block doesn't make the TV :notempty, it only makes the value in the database notempty.
MIGX should counter for that.
