### ISSUE TITLE
Update to 2.8.2 issue with migx & media sources - not creating directories using migxObjectMediaPath

### ISSUE THREAD

**Issue by BigBlockStudios** [Bruno17/MIGX#369]
I have a migx config that creates directories in 2 specific media sources for a project manager tool within the modx manager.
The directories are no longer automatically created after the update to 2.8.2

The tools process is:

- create and save a new project
- the code will then create the directories for that project in the media sources (not working)
- the media sources basepath and baseurl are defined as:

[[!migxObjectMediaPath? &pathTpl=assets/projects/{id}/documents/ &createFolder=1]]

So here is the funny part ... all I have to do is view the Media->Media Sources page, I don't even have to open the specific media source ... and the directories will be created - the user can return to the project and start adding files.

Seems to be cache related so I am including the core/cache/media_sources/web/source.cache.php files (which looks very odd) and the migx configs

[source.cache.txt](https://github.com/Bruno17/MIGX/files/6435709/source.cache.txt)

[migx-config.txt](https://github.com/Bruno17/MIGX/files/6435724/migx-config.txt)

**Comment by Bruno17** [comment]
As of 
https://github.com/modxcms/revolution/issues/15707
this is not related to the MODX upgrade and seems it was allways like that before.

This is by design, that folders are only created, when you are within a MIGXdb - CMP, where the SESSION - Var migxWorkingObjectid is set by the processor.

If you need other behaviour, its propably better to create your own copy of that snippet.
Otherwise it will get overridden by upgrades.
